version: '3.9'

services:
  postgres:
    image: davon/postgres
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - postgres_data:/data/davon-postgres
    restart: unless-stopped

  web:
    image: davon/poetriumph
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${POETRIUMPH_CONTAINER_NAME}
    environment:
      SECRET_KEY: ${SECRET_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    ports:
      - "8008:8000"
    depends_on:
      - postgres

volumes:
    postgres_data:
      external: true
