version: '3.9'

services:
  postgres:
    image: poetriumph/postgres
    build:
      context: .
      dockerfile: ./docker/postgres_image/Dockerfile
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - postgres_data_poetry:/data/davon-postgres
    restart: unless-stopped
    networks:
      - network
    ports:
      - "5432:5432"

  redis:
    image: poetriumph/redis
    build:
      context: .
      dockerfile: ./docker/redis_image/Dockerfile
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "6379:6379"
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  postgres_data_poetry:
    external: true
