# Generated by Django 4.2.4 on 2023-08-16 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=50)),
                ('user_text', models.TextField()),
                ('text', models.TextField()),
                ('source_lang', models.CharField(choices=[('auto', 'Detect language'), ('english', 'English'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('italian', 'Italian'), ('french', 'French'), ('german', 'German'), ('hindi', 'Hindi'), ('arabic', 'Arabic'), ('portuguese', 'Portuguese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese (simplified)', 'Chinese Simplified'), ('chinese (traditional)', 'Chinese Traditional'), ('turkish', 'Turkish'), ('indonesian', 'Indonesian')], max_length=30)),
                ('target_lang', models.CharField(choices=[('auto', 'Detect language'), ('english', 'English'), ('russian', 'Russian'), ('spanish', 'Spanish'), ('italian', 'Italian'), ('french', 'French'), ('german', 'German'), ('hindi', 'Hindi'), ('arabic', 'Arabic'), ('portuguese', 'Portuguese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese (simplified)', 'Chinese Simplified'), ('chinese (traditional)', 'Chinese Traditional'), ('turkish', 'Turkish'), ('indonesian', 'Indonesian')], max_length=30)),
                ('language_engine', models.CharField(choices=[('GoogleTranslator', 'Google Translator'), ('ChatGptTranslator', 'ChatGPT Translator'), ('ChatGpt_Bot', 'ChatGPT Poet')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
