# Generated by Django 4.2.4 on 2023-12-14 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=50)),
                ('author', models.CharField(blank=True, default='', max_length=50)),
                ('original_text', models.TextField()),
                ('translation', models.TextField()),
                ('source_lang', models.CharField(choices=[('auto', 'Detect language'), ('english', 'English'), ('spanish', 'Spanish'), ('russian', 'Russian'), ('hindi', 'Hindi'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('french', 'French'), ('german', 'German'), ('ukrainian', 'Ukrainian'), ('arabic', 'Arabic'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese (simplified)', 'Chinese Simplified'), ('chinese (traditional)', 'Chinese Traditional'), ('turkish', 'Turkish'), ('indonesian', 'Indonesian')], max_length=30)),
                ('target_lang', models.CharField(choices=[('auto', 'Detect language'), ('english', 'English'), ('spanish', 'Spanish'), ('russian', 'Russian'), ('hindi', 'Hindi'), ('italian', 'Italian'), ('portuguese', 'Portuguese'), ('french', 'French'), ('german', 'German'), ('ukrainian', 'Ukrainian'), ('arabic', 'Arabic'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('chinese (simplified)', 'Chinese Simplified'), ('chinese (traditional)', 'Chinese Traditional'), ('turkish', 'Turkish'), ('indonesian', 'Indonesian')], max_length=30)),
                ('language_engine', models.CharField(choices=[('GoogleTranslator', 'Google Translator'), ('ChatGptTranslator', 'ChatGPT Translator'), ('ChatGpt_Poet', 'ChatGPT Poet')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_hidden', models.BooleanField(default=True)),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
