# Generated by Django 4.2.3 on 2023-08-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
        migrations.AlterField(
            model_name='poem',
            name='language_engine',
            field=models.CharField(choices=[('GoogleTranslator', 'Google Translator'), ('ChatGptTranslator', 'ChatGPT Translator'), ('ChatGpt_Bot', 'ChatGPT Bot')], max_length=20),
        ),
    ]
