# Generated by Django 4.2.4 on 2023-08-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_translation', '0002_alter_poem_options_poem_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
