# Generated by Django 4.2.4 on 2023-08-03 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_translation', '0003_poem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='language_engine',
            field=models.CharField(choices=[('GoogleTranslator', 'Google Translator'), ('ChatGptTranslator', 'ChatGPT Translator'), ('ChatGpt_Bot', 'ChatGPT Poet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='poem',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
