# Generated by Django 4.2.4 on 2023-08-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poetry_translation', '0005_alter_poem_source_lang_alter_poem_target_lang_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
